### ISSUE TITLE
Program.optsObj really? Why not simply program.opts ??

### ISSUE THREAD

**Issue by lekhnath** [bySabi/safe-commander.js#2]

**Comment by bySabi** [comment]
This package don´t pretend to be a fork or rewrite of `Command.js`, is just a workaround to solve a design flaw.
[opts](https://github.com/tj/commander.js/blob/master/index.js#L753) is a function of Command prototype. `optsObj` was the best name that no collide with current Command namespace.

If you have a better name, please let me know it.

**Comment by lekhnath** [comment]
Lets' stick with `optsObj` then. :)

**Comment by specious** [comment]
Why not `options`?  I feel like `optsObj` is making my code ugly.

`if (program.options.bbqSauce) { ...`

**Comment by bySabi** [comment]
@specious `options` is used on Commander.js implementation:
* https://github.com/tj/commander.js/blob/master/index.js#L83
* https://github.com/tj/commander.js/blob/master/index.js#L394
* https://github.com/tj/commander.js/blob/master/index.js#L667

**Comment by specious** [comment]
How about `safeOpts`?

**Comment by bySabi** [comment]
is a good name.
Let me make some changes.

**Comment by bySabi** [comment]
Is done! ... `Program.optsObj` now is `Program.safeOpts` in new release `3.0.0`

**Comment by specious** [comment]
I was curious what would happen to the version.  I kind of liked that safe-commander was tracking the parent library.

**Comment by bySabi** [comment]
@specious you are right, I forget the command.js/safe-commander.js version pair. 

Maybe we can back to, say `2.11.2`, and make `safeOpts` an alias of `optsObj`
It seems your one of three developer using `safe-commander` right now :-)

**Comment by specious** [comment]
I just checked, npm allows to [unpublish](https://docs.npmjs.com/cli/unpublish) a version:

> With the default registry (registry.npmjs.org), unpublish is only allowed with versions published in the last 24 hours. If you are trying to unpublish a version published longer ago than that, contact support@npmjs.com.

Since safe-commander usage hasn't grown yet, I'd consider hard reseting master to 538f785c19716c73853edae804149e10ed1dc5df and deferring this change until the next versioned release.

**Comment by bySabi** [comment]
Thanks for tips :-)
I unpublish it and put latest commit in a separate branch: https://github.com/bySabi/safe-commander.js/tree/safe_opts

it will release on next `commander.js`
