### ISSUE TITLE
FYI: Proposed addition to Commander to solve option name collisions

### ISSUE THREAD

**Issue by shadowspawn** [bySabi/safe-commander.js#5]
I saw this project mentioned in: https://github.com/tj/commander.js/issues/648 

For your information, letting you know there is work is on progress to solve the option name collisions in Commander: https://github.com/tj/commander.js/pull/1102

**Comment by bySabi** [comment]
This is great @shadowspawn, I hope this problem is resolved at once.

good work!

**Comment by shadowspawn** [comment]
`.storeOptionsAsProperties` shipped in Commander v4.1

https://github.com/tj/commander.js#avoiding-option-name-clashes
